server:
    image: idocking/go-pandoc:latest
    command: ["./go-pandoc", "run"]
    ports:
      - 9092:9092
    volumes:
      - ./templates:/app/templates
      - ./data:/app/data
      - ./app.conf:/app/app.conf
